volumes:
  pg_data:
  static:
  media:
  frontend_static:

services:
  db:
    image: postgres:13
    env_file: ../.env
    container_name: foodgram_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: foodgram-back
    image: anzorgreen/foodgram_backend:v1
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/


  frontend:
    container_name: foodgram-front
    image: anzorgreen/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/var/www/foodgram/media/
