# Generated by Django 5.1.4 on 2025-03-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='cooking_time_validation',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='amount_validation',
        ),
    ]
